language: python
python:
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
env:
- DEPLOY=TEST
services:
- mysql
install: pip install -r requirements.txt
script:
- fab localhost init_db
- pytest tests/
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS attendance_system;'
- openssl aes-256-cbc -K $encrypted_cfd433a023ff_key -iv $encrypted_cfd433a023ff_iv
  -in config.py.enc -out config.py -d